USE testdb;

DROP TABLE IF EXISTS olts;

CREATE TABLE olts (
    olt_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    olt_code VARCHAR(50) UNIQUE NOT NULL,
    service_area_id BIGINT,
    olt_type VARCHAR(50),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
